[fix] - Header Menu Size
atk4/ui pull request #1151
Opened 2020-04-29 19:05 UTC by ibelar

Make sure there is no gap between the top and navigation menu.

2020-05-01 17:39 UTC, ibelar commented
Fix #1156

2020-05-01 17:41 UTC, mvorisek commented
> 
> 
> Fix #1156

Added my CSS rules to that issue, see. And add "fix #nn" text always to the issue description, otherwise it does not work, ie. the issue will be not closed otherwise.

2020-05-01 17:55 UTC, mvorisek requested changes

2020-05-01 17:55 UTC, mvorisek commented on public/agileui.css
> +  z-index: 99;
Not a fix to #1156

2020-05-01 19:28 UTC, mvorisek approved these changes

2020-05-01 19:28 UTC, mvorisek commented on public/agileui.css
> +  z-index: 99;
Not sure what this should fix on #1156, but otherwise PR is read to be merged

2020-05-01 22:41 UTC, mvorisek commented
@ibelar #1156 should be fixed, please review carefully and better rerun less build, I edited it manually.

2020-05-02 14:11 UTC, DarkSide666 approved these changes
Fixes issue for me, so LGTM

2020-05-02 14:12 UTC, merged

2020-05-02 14:22 UTC, mvorisek commented
> Fixes issue for me, so LGTM

@DarkSide666 because I fixed it :)

2020-05-02 14:33 UTC, DarkSide666 commented
Thank you! :)

2020-05-02 20:14 UTC, mkrecek234 commented
Still have the same issue, no change: Looks like that (with Maestro theme) - also manually changing the z-index does not have an effect :
![image](https://user-images.githubusercontent.com/28671486/80891120-3e00b800-8cc2-11ea-88b2-5f661f93aadb.png)

2020-05-02 21:04 UTC, ibelar commented
Are you pulling css locally or via jsDeliver? If from jsDeliver, then give it a day at least to be updates correctly.

2020-05-02 22:00 UTC, mvorisek commented
> 
> 
> Are you pulling css locally or via jsDeliver? If from jsDeliver, then give it a day at least to be updates correctly.

PR https://github.com/atk4/ui/pull/1168 for faster collaboration ? @mkrecek234 does this help?

PS using old Admin, Maestro might need more work, please double check/fix my commits if needed.

2020-05-03 19:40 UTC, mkrecek234 commented
Works now, probably then was that caching/CDN delay problem. Is it intentional to have a vertical line right to the app header? I think before there was none, probably again subjective, but looked better to me, more as a title, than a menu: 
<img width="311" alt="Ohne Titel" src="https://user-images.githubusercontent.com/28671486/80923921-a9ac5900-8d86-11ea-9052-d2dfbcede99b.png">

2020-05-03 19:43 UTC, mvorisek commented
@mkrecek234 Great, thank you for your fbk. This PR should have no affect on the horizontal/top panel excep the updated height.