Fix wrong URL fallbacks
atk4/ui pull request #1167
Opened 2020-05-02 17:44 UTC by mvorisek

The fallbacks were wrong as the expected the App to be called in the same dir - with subdirectory, the files were failing to load.

There is no need for them as they are set by defaut and can be set to `../public` by user if needed.

2020-05-04 22:26 UTC, romaninsh requested changes
Currently user can create "public" folder and the files would be included from it locally. If this PR goes through, we'll be always using CDN.

Commercial projects would typically use locally generated files, so to me it seems like a BC break.

2020-05-04 22:39 UTC, mvorisek commented
Explained in the description why this is wrong. Bad usage can be very easily solved by setting the cdns locally.

2020-05-05 20:43 UTC, DarkSide666 commented
Idea as such is good - developer can always set cdn = '../public' himself, but still this is small compatibility break.

2020-05-11 23:15 UTC, mvorisek commented
@romaninsh so ok?

2020-05-14 13:40 UTC, romaninsh commented
I'm not against this change but it will be a BC.

2020-05-14 13:44 UTC, romaninsh commented
@mvorisek - we're still trying to figure out a good way to deal with breaking changes. Last meeting we agreed to label those issues and if any of the issues with BC are to be merged, we would need to issue a new minor release, e.g. 2.1.x.

It would also be important for all the breaking changes to provide a guide no how to update check if your app is affected and how to upgrade. It would be nice to see this mechanism working!

I'll raise some awareness of this issue and we can pilot it forward.

Ideally we would also need a guide in the documentation explaining how to implement local file builds.

2020-05-14 13:56 UTC, romaninsh commented
@mvorisek I'd like to deal with https://github.com/atk4/ui/issues/1189 this weekend and send out 2.1 release for ATK UI. After that I'll merge this PR.

Until then - please provide a guide how existing projects can "identify" BC break and prepare for it ahead of time.

2020-05-14 14:19 UTC, mvorisek commented
> Until then - please provide a guide how existing projects can "identify" BC break and prepare for it ahead of time.

I have already proposed simple changelog/migration guide on Wiki. Anyone can then "identify BC breaks" on that. All BC breaks should target to always reject wrong/original input.

2020-05-18 10:10 UTC, mvorisek commented
Removed "BLOCKED" as "BC-break" is enought. This change should not affect almost any user (if any) as the CDNs are normally set by default, thus no fallback.

2020-06-01 21:59 UTC, DarkSide666 approved these changes
You can always set `$this->cdn['jquery'] = '../public'` and then it will be compatible, so this is actually quite small BC break. Good to merge.

2020-06-01 22:00 UTC, merged