Add word "dangerously" to template setters names
atk4/ui pull request #1509
Opened 2020-10-25 17:18 UTC by mvorisek

like React and other frameworks do - having html setter itself is not dangerous, but you really must know what are you doing

2020-10-25 17:39 UTC, mvorisek commented on src/Form/Control/Input.php
> +        $this->template->dangerouslySetHtml('Input', $this->getInput());
@georgehristov is this correct? Can you please review this PR if there are more simillar issues?

2020-10-25 18:16 UTC, mvorisek commented on demos/javascript/vue-component.php
> +$clock->template->dangerouslyTrySetHtml('script', $clock_script);
we should set using JS Expr

2020-10-25 18:17 UTC, mvorisek commented on src/App.php
> +        $this->html->template->dangerouslyAppendHtml('HEAD', $this->getTag('style', $style));
better to rename getTagHtml()

2020-10-25 18:18 UTC, mvorisek commented on src/App.php
> +            $this->html->template->dangerouslyAppendHtml('HEAD', $this->html->getJs());
better to rename to getJsHtml or refactor

2020-10-25 18:18 UTC, mvorisek commented on src/App.php
> +        $this->html->template->dangerouslyAppendHtml('HEAD', $this->getTag('script', ['src' => $url, 'defer' => $isDefer, 'async' => $isAsync], '') . "\n");
same

2020-10-25 18:18 UTC, mvorisek commented on src/App.php
> +        $this->html->template->dangerouslyAppendHtml('HEAD', $this->getTag('link/', ['rel' => 'stylesheet', 'type' => 'text/css', 'href' => $url]) . "\n");
same

2020-10-25 18:19 UTC, mvorisek commented on src/Form/Control/Multiline.php
> +        $this->multiLine->template->dangerouslyTrySetHtml('Input', $this->getInput());
same

2020-10-25 18:19 UTC, mvorisek commented on src/Form/Control/TreeItemSelector.php
> +        $this->itemSelector->template->dangerouslyTrySetHtml('Input', $this->getInput());
same

2020-10-25 18:20 UTC, mvorisek commented on src/GridLayout.php
> +        $this->t_wrap->dangerouslyAppendHtml('rows', '{rows}');
we should build using objects

2020-10-25 18:20 UTC, mvorisek commented on src/Layout/Centered.php
> +            $this->template->dangerouslyTrySetHtml('HeaderImage', '<img class="ui image" src="' . $this->image . '" alt="' . $this->image_alt . '" />');
later, build with OOP

2020-10-25 18:21 UTC, mvorisek commented on src/Lister.php
> +                    $this->template->dangerouslyAppendHtml('rows', $empty);
better to uise OOP

2020-10-25 18:21 UTC, mvorisek commented on src/Lister.php
> +            $this->template->dangerouslyAppendHtml('rows', $html);
same

2020-10-25 18:21 UTC, mvorisek commented on src/UserAction/ModalExecutor.php
> +                $preview->template->dangerouslySetHtml('Content', $text);
is should not be named `text` if can be html

2020-10-25 18:22 UTC, mvorisek commented on src/View.php
> +            $this->template->dangerouslySetHtml('attributes', implode(' ', $tmp));
use OOP

2020-10-25 18:51 UTC, DarkSide666 requested changes
In my opinion this is useless PR.
Create new BC break because of just renaming methods to "dangerous" methods... It gives developer no advantage, just new BC breaks.

2020-10-25 19:09 UTC, mvorisek commented
> 
> 
> In my opinion this is useless PR.
> Create new BC break because of just renaming methods to "dangerous" methods... It gives developer no advantage, just new BC breaks.

this one is quote important so noone missuse the setHtml methods, this is how React/FB or Google code is written.

2020-10-26 14:09 UTC, DarkSide666 approved these changes
Well... OK :)

2020-10-27 17:29 UTC, merged